name: docker-github

on:
 workflow_dispatch:

jobs:
  build:
     runs-on: ubuntu-latest
     defaults:
        run:
          working-directory: ./WebApplication1

     steps:
      - uses: actions/checkout@v4

      - name: docker build
        run: pwd
   
      
     
