name: docker-github

on:
  push:

jobs:
  check:
     runs-on: ubuntu-latest
     defaults:
        run:
          working-directory: ./WebApplication1

     steps:
      - uses: actions/checkout@v4

      - name: docker build
        run: |
           pwd
           ls -lrth

  Build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./WebApplication1

    steps:
    - uses: actions/checkout@v4
    
    - name: docker build
      run: docker build -t nihar15759/dockertest:latest .
     
