name: Dotnet-Publish

on:
 push

jobs:
  dotnetbuild:
     runs-on:
        ubuntu-latest

     steps:
       - uses: actions/checkout@v4

       - name: DotNet Setup 
         uses: actions/setup-dotnet@v4
         with:
              dotnet-version: '3.1.x'

       - name: dotnet restore
         run: |
            cd WebApplication1
            dotnet restore

       - name: dotnet publish
         run: |
            cd WebApplication1
            dotnet publish -c release -o ./github_output

       - name: dotnet build
         run: |
            cd WebApplication1
            dotnet build
            
