name: Dotnet-Publish

on:
 workflow_dispatch

concurrency:
     group: ${{ github.repository }}-concurrency-for-workflow
     cancel-in-progress: false

jobs:
  deploy:
   concurrency: 
     group: ${{ github.repository }}-concurrency-for-workflow
   runs-on: ubuntu-latest

   steps:
       - uses: actions/checkout@v4

       - name: DotNet Setup 
         uses: actions/setup-dotnet@v4
         with:
              dotnet-version: '3.1.x'

       - name: dotnet restore
         run: |
            cd WebApplication1
            dotnet restore

       - name: dotnet build
         run: |
            cd WebApplication1
            dotnet build

       
       - name: dotnet publish
         run: |
            cd WebApplication1
            dotnet publish -c release -o ./github_output

       - uses: actions/upload-artifact@v4
         with:
            name: upload-artifact
            path: ./WebApplication1/github_output

       - uses: actions/download-artifact@v4
         with:
              name: upload-artifact
              path: ./Test
