# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
          cd DotNet
          dotnet restore
    - name: DotNet Build
      run: |
         cd DotNet
         dotnet build
    - name: DotNet test
      run: |
         cd DotNet
         dotnet test
    - name: DotNet Publish
      run: |
         cd DotNet
         dotnet publish
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
          name: assets-for-download
          path: downloads
      
