name: grok-test

on:
  workflow_dispatch:
    inputs:
      environent:
        description: 'Select environment'
        type: choice
        required: true
        options:
          - dev
          - prod
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.targetEnv }}
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.targetEnv }}"
