name: input-develop

on:
 push:
   branches:
     - Develop

env:
  test_value: "somevalue"

jobs:
  run-input:
    runs-on: [ubuntu-latest]
    defaults:
     run:
      shell: bash
      working-directory: ./src

    steps:
      - uses: actions/checkout@v4.2.2
        continue-on-error: true

      - run: echo ${{ env.test_value }}
        id: test-output-generate
      
     
