name: Dotnet_docker

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApplication1
    
    steps:
     - uses: actions/checkout@v4
          
     - uses: docker/login-action@v3
       with:
          username: nihar15759
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
     - name: Build the Docker image
       run: |
          cd WebApplication1 
          docker build -t nihar15759/dockertest_github:latest -f Dockerfile

     - name: Push the Docker image
       run: |
          docker push nihar15759/dotnet-github
