name: Dotnet_docker

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApplication1
    
    steps:
     - uses: actions/checkout@v4
          
     - uses: docker/login-action@v3
       with:
          username: nihar15759
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
       with:
          images: nihar15759/docker_github

     - name: Build and push Docker image
       id: push
       uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
       with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
