name: Dotnet_docker

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v4  

     - name: Docker Build
       run: |
          cd WebApplication1
          docker build -t nihar15759\docker_github:latest -f Dockerfile .
          
     - uses: docker/login-action@v3
       with:
          username: nihar15759
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
  
   
   
