name: input-develop

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'Application version to deploy'
        type: string
        required: true
        default: '1.0.0'
       
env:
  test_value: "somevalue"

jobs:
 run-input:
    runs-on: [ubuntu-latest]
    defaults:
     run:
      shell: bash
      working-directory: ./src

    steps:
      - uses: actions/checkout@v4.2.2
        continue-on-error: true

      - run: echo ${{ env.test_value }}
        id: test-output-generate
     
